name: Build Image Optimizer

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Clean old build files
        run: |
          if exist build rmdir /s /q build
          if exist dist rmdir /s /q dist
        shell: cmd

      - name: Build Windows EXE
        run: |
          pyinstaller -y --onefile --windowed --name "PartHive Image Optimizer" --icon=icon.ico --collect-all tkinterdnd2 --add-data "icon.png;." app.py

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Clean old build files
        run: |
          rm -rf build dist icon.iconset icon.icns

      - name: Create ICNS icon
        run: |
          mkdir icon.iconset

          sips -z 16 16     icon.png --out icon.iconset/icon_16x16.png
          sips -z 32 32     icon.png --out icon.iconset/icon_16x16@2x.png
          sips -z 32 32     icon.png --out icon.iconset/icon_32x32.png
          sips -z 64 64     icon.png --out icon.iconset/icon_32x32@2x.png
          sips -z 128 128   icon.png --out icon.iconset/icon_128x128.png
          sips -z 256 256   icon.png --out icon.iconset/icon_128x128@2x.png
          sips -z 256 256   icon.png --out icon.iconset/icon_256x256.png
          sips -z 512 512   icon.png --out icon.iconset/icon_256x256@2x.png
          sips -z 512 512   icon.png --out icon.iconset/icon_512x512.png
          cp icon.png icon.iconset/icon_512x512@2x.png

          iconutil -c icns icon.iconset -o icon.icns

      - name: Build macOS app
        run: |
          pyinstaller -y --windowed --name "PartHive Image Optimizer" --icon=icon.icns --collect-all tkinterdnd2 --add-data "icon.png:." app.py

      - name: Upload Mac build
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/